services:
  mongo:
    image: mongo:7
    ports: [ "27017:27017" ]
    volumes: [ "./docker-data/mongo:/data/db" ]
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports: [ "6379:6379" ]
    volumes: [ "./docker-data/redis:/data" ]
